export interface Provinsi {
  kode: string
  nama: string
}

export interface KabupatenKota {
  kode: string
  nama: string
  provinsi_kode: string
}

export const PROVINSI: Provinsi[] = [
  { kode: '11', nama: 'ACEH' },
  { kode: '12', nama: 'SUMATERA UTARA' },
  { kode: '13', nama: 'SUMATERA BARAT' },
  { kode: '14', nama: 'RIAU' },
  { kode: '15', nama: 'JAMBI' },
  { kode: '16', nama: 'SUMATERA SELATAN' },
  { kode: '17', nama: 'BENGKULU' },
  { kode: '18', nama: 'LAMPUNG' },
  { kode: '19', nama: 'KEPULAUAN BANGKA BELITUNG' },
  { kode: '21', nama: 'KEPULAUAN RIAU' },
  { kode: '31', nama: 'DKI JAKARTA' },
  { kode: '32', nama: 'JAWA BARAT' },
  { kode: '33', nama: 'JAWA TENGAH' },
  { kode: '34', nama: 'DI YOGYAKARTA' },
  { kode: '35', nama: 'JAWA TIMUR' },
  { kode: '36', nama: 'BANTEN' },
  { kode: '51', nama: 'BALI' },
  { kode: '52', nama: 'NUSA TENGGARA BARAT' },
  { kode: '53', nama: 'NUSA TENGGARA TIMUR' },
  { kode: '61', nama: 'KALIMANTAN BARAT' },
  { kode: '62', nama: 'KALIMANTAN TENGAH' },
  { kode: '63', nama: 'KALIMANTAN SELATAN' },
  { kode: '64', nama: 'KALIMANTAN TIMUR' },
  { kode: '65', nama: 'KALIMANTAN UTARA' },
  { kode: '71', nama: 'SULAWESI UTARA' },
  { kode: '72', nama: 'SULAWESI TENGAH' },
  { kode: '73', nama: 'SULAWESI SELATAN' },
  { kode: '74', nama: 'SULAWESI TENGGARA' },
  { kode: '75', nama: 'GORONTALO' },
  { kode: '76', nama: 'SULAWESI BARAT' },
  { kode: '81', nama: 'MALUKU' },
  { kode: '82', nama: 'MALUKU UTARA' },
  { kode: '91', nama: 'PAPUA BARAT' },
  { kode: '92', nama: 'PAPUA TENGAH' },
  { kode: '93', nama: 'PAPUA PEGUNUNGAN' },
  { kode: '94', nama: 'PAPUA' },
  { kode: '95', nama: 'PAPUA SELATAN' },
  { kode: '96', nama: 'PAPUA BARAT DAYA' },
]

export const KABUPATEN_KOTA: KabupatenKota[] = [
  // Aceh (11)
  { kode: '11.01', nama: 'KABUPATEN SIMEULUE', provinsi_kode: '11' },
  { kode: '11.02', nama: 'KABUPATEN ACEH SINGKIL', provinsi_kode: '11' },
  { kode: '11.03', nama: 'KABUPATEN ACEH SELATAN', provinsi_kode: '11' },
  { kode: '11.04', nama: 'KABUPATEN ACEH TENGGARA', provinsi_kode: '11' },
  { kode: '11.05', nama: 'KABUPATEN ACEH TIMUR', provinsi_kode: '11' },
  { kode: '11.06', nama: 'KABUPATEN ACEH TENGAH', provinsi_kode: '11' },
  { kode: '11.07', nama: 'KABUPATEN ACEH BARAT', provinsi_kode: '11' },
  { kode: '11.08', nama: 'KABUPATEN ACEH BESAR', provinsi_kode: '11' },
  { kode: '11.09', nama: 'KABUPATEN PIDIE', provinsi_kode: '11' },
  { kode: '11.10', nama: 'KABUPATEN BIREUEN', provinsi_kode: '11' },
  { kode: '11.11', nama: 'KABUPATEN ACEH UTARA', provinsi_kode: '11' },
  { kode: '11.12', nama: 'KABUPATEN ACEH BARAT DAYA', provinsi_kode: '11' },
  { kode: '11.13', nama: 'KABUPATEN GAYO LUES', provinsi_kode: '11' },
  { kode: '11.14', nama: 'KABUPATEN ACEH TAMIANG', provinsi_kode: '11' },
  { kode: '11.15', nama: 'KABUPATEN NAGAN RAYA', provinsi_kode: '11' },
  { kode: '11.16', nama: 'KABUPATEN ACEH JAYA', provinsi_kode: '11' },
  { kode: '11.17', nama: 'KABUPATEN BENER MERIAH', provinsi_kode: '11' },
  { kode: '11.18', nama: 'KABUPATEN PIDIE JAYA', provinsi_kode: '11' },
  { kode: '11.71', nama: 'KOTA BANDA ACEH', provinsi_kode: '11' },
  { kode: '11.72', nama: 'KOTA SABANG', provinsi_kode: '11' },
  { kode: '11.73', nama: 'KOTA LANGSA', provinsi_kode: '11' },
  { kode: '11.74', nama: 'KOTA LHOKSEUMAWE', provinsi_kode: '11' },
  { kode: '11.75', nama: 'KOTA SUBULUSSALAM', provinsi_kode: '11' },
  // Sumatera Utara (12)
  { kode: '12.01', nama: 'KABUPATEN NIAS', provinsi_kode: '12' },
  { kode: '12.02', nama: 'KABUPATEN MANDAILING NATAL', provinsi_kode: '12' },
  { kode: '12.03', nama: 'KABUPATEN TAPANULI SELATAN', provinsi_kode: '12' },
  { kode: '12.04', nama: 'KABUPATEN TAPANULI TENGAH', provinsi_kode: '12' },
  { kode: '12.05', nama: 'KABUPATEN TAPANULI UTARA', provinsi_kode: '12' },
  { kode: '12.06', nama: 'KABUPATEN TOBA', provinsi_kode: '12' },
  { kode: '12.07', nama: 'KABUPATEN LABUHANBATU', provinsi_kode: '12' },
  { kode: '12.08', nama: 'KABUPATEN ASAHAN', provinsi_kode: '12' },
  { kode: '12.09', nama: 'KABUPATEN SIMALUNGUN', provinsi_kode: '12' },
  { kode: '12.10', nama: 'KABUPATEN DAIRI', provinsi_kode: '12' },
  { kode: '12.11', nama: 'KABUPATEN KARO', provinsi_kode: '12' },
  { kode: '12.12', nama: 'KABUPATEN DELI SERDANG', provinsi_kode: '12' },
  { kode: '12.13', nama: 'KABUPATEN LANGKAT', provinsi_kode: '12' },
  { kode: '12.14', nama: 'KABUPATEN NIAS SELATAN', provinsi_kode: '12' },
  { kode: '12.15', nama: 'KABUPATEN HUMBANG HASUNDUTAN', provinsi_kode: '12' },
  { kode: '12.16', nama: 'KABUPATEN PAKPAK BHARAT', provinsi_kode: '12' },
  { kode: '12.17', nama: 'KABUPATEN SAMOSIR', provinsi_kode: '12' },
  { kode: '12.18', nama: 'KABUPATEN SERDANG BEDAGAI', provinsi_kode: '12' },
  { kode: '12.19', nama: 'KABUPATEN BATU BARA', provinsi_kode: '12' },
  { kode: '12.20', nama: 'KABUPATEN PADANG LAWAS UTARA', provinsi_kode: '12' },
  { kode: '12.21', nama: 'KABUPATEN PADANG LAWAS', provinsi_kode: '12' },
  { kode: '12.22', nama: 'KABUPATEN LABUHANBATU SELATAN', provinsi_kode: '12' },
  { kode: '12.23', nama: 'KABUPATEN LABUHANBATU UTARA', provinsi_kode: '12' },
  { kode: '12.24', nama: 'KABUPATEN NIAS UTARA', provinsi_kode: '12' },
  { kode: '12.25', nama: 'KABUPATEN NIAS BARAT', provinsi_kode: '12' },
  { kode: '12.71', nama: 'KOTA SIBOLGA', provinsi_kode: '12' },
  { kode: '12.72', nama: 'KOTA TANJUNGBALAI', provinsi_kode: '12' },
  { kode: '12.73', nama: 'KOTA PEMATANGSIANTAR', provinsi_kode: '12' },
  { kode: '12.74', nama: 'KOTA TEBING TINGGI', provinsi_kode: '12' },
  { kode: '12.75', nama: 'KOTA MEDAN', provinsi_kode: '12' },
  { kode: '12.76', nama: 'KOTA BINJAI', provinsi_kode: '12' },
  { kode: '12.77', nama: 'KOTA PADANGSIDIMPUAN', provinsi_kode: '12' },
  { kode: '12.78', nama: 'KOTA GUNUNGSITOLI', provinsi_kode: '12' },
  // Sumatera Barat (13)
  { kode: '13.01', nama: 'KABUPATEN KEPULAUAN MENTAWAI', provinsi_kode: '13' },
  { kode: '13.02', nama: 'KABUPATEN PESISIR SELATAN', provinsi_kode: '13' },
  { kode: '13.03', nama: 'KABUPATEN SOLOK', provinsi_kode: '13' },
  { kode: '13.04', nama: 'KABUPATEN SIJUNJUNG', provinsi_kode: '13' },
  { kode: '13.05', nama: 'KABUPATEN TANAH DATAR', provinsi_kode: '13' },
  { kode: '13.06', nama: 'KABUPATEN PADANG PARIAMAN', provinsi_kode: '13' },
  { kode: '13.07', nama: 'KABUPATEN AGAM', provinsi_kode: '13' },
  { kode: '13.08', nama: 'KABUPATEN LIMA PULUH KOTA', provinsi_kode: '13' },
  { kode: '13.09', nama: 'KABUPATEN PASAMAN', provinsi_kode: '13' },
  { kode: '13.10', nama: 'KABUPATEN SOLOK SELATAN', provinsi_kode: '13' },
  { kode: '13.11', nama: 'KABUPATEN DHARMASRAYA', provinsi_kode: '13' },
  { kode: '13.12', nama: 'KABUPATEN PASAMAN BARAT', provinsi_kode: '13' },
  { kode: '13.71', nama: 'KOTA PADANG', provinsi_kode: '13' },
  { kode: '13.72', nama: 'KOTA SOLOK', provinsi_kode: '13' },
  { kode: '13.73', nama: 'KOTA SAWAHLUNTO', provinsi_kode: '13' },
  { kode: '13.74', nama: 'KOTA PADANG PANJANG', provinsi_kode: '13' },
  { kode: '13.75', nama: 'KOTA BUKITTINGGI', provinsi_kode: '13' },
  { kode: '13.76', nama: 'KOTA PAYAKUMBUH', provinsi_kode: '13' },
  { kode: '13.77', nama: 'KOTA PARIAMAN', provinsi_kode: '13' },
  // Riau (14)
  { kode: '14.01', nama: 'KABUPATEN KUANTAN SINGINGI', provinsi_kode: '14' },
  { kode: '14.02', nama: 'KABUPATEN INDRAGIRI HULU', provinsi_kode: '14' },
  { kode: '14.03', nama: 'KABUPATEN INDRAGIRI HILIR', provinsi_kode: '14' },
  { kode: '14.04', nama: 'KABUPATEN PELALAWAN', provinsi_kode: '14' },
  { kode: '14.05', nama: 'KABUPATEN SIAK', provinsi_kode: '14' },
  { kode: '14.06', nama: 'KABUPATEN KAMPAR', provinsi_kode: '14' },
  { kode: '14.07', nama: 'KABUPATEN ROKAN HULU', provinsi_kode: '14' },
  { kode: '14.08', nama: 'KABUPATEN BENGKALIS', provinsi_kode: '14' },
  { kode: '14.09', nama: 'KABUPATEN ROKAN HILIR', provinsi_kode: '14' },
  { kode: '14.10', nama: 'KABUPATEN KEPULAUAN MERANTI', provinsi_kode: '14' },
  { kode: '14.71', nama: 'KOTA PEKANBARU', provinsi_kode: '14' },
  { kode: '14.73', nama: 'KOTA DUMAI', provinsi_kode: '14' },
  // Jambi (15)
  { kode: '15.01', nama: 'KABUPATEN KERINCI', provinsi_kode: '15' },
  { kode: '15.02', nama: 'KABUPATEN MERANGIN', provinsi_kode: '15' },
  { kode: '15.03', nama: 'KABUPATEN SAROLANGUN', provinsi_kode: '15' },
  { kode: '15.04', nama: 'KABUPATEN BATANGHARI', provinsi_kode: '15' },
  { kode: '15.05', nama: 'KABUPATEN MUARO JAMBI', provinsi_kode: '15' },
  { kode: '15.06', nama: 'KABUPATEN TANJUNG JABUNG TIMUR', provinsi_kode: '15' },
  { kode: '15.07', nama: 'KABUPATEN TANJUNG JABUNG BARAT', provinsi_kode: '15' },
  { kode: '15.08', nama: 'KABUPATEN TEBO', provinsi_kode: '15' },
  { kode: '15.09', nama: 'KABUPATEN BUNGO', provinsi_kode: '15' },
  { kode: '15.71', nama: 'KOTA JAMBI', provinsi_kode: '15' },
  { kode: '15.72', nama: 'KOTA SUNGAI PENUH', provinsi_kode: '15' },
  // Sumatera Selatan (16)
  { kode: '16.01', nama: 'KABUPATEN OGAN KOMERING ULU', provinsi_kode: '16' },
  { kode: '16.02', nama: 'KABUPATEN OGAN KOMERING ILIR', provinsi_kode: '16' },
  { kode: '16.03', nama: 'KABUPATEN MUARA ENIM', provinsi_kode: '16' },
  { kode: '16.04', nama: 'KABUPATEN LAHAT', provinsi_kode: '16' },
  { kode: '16.05', nama: 'KABUPATEN MUSI RAWAS', provinsi_kode: '16' },
  { kode: '16.06', nama: 'KABUPATEN MUSI BANYUASIN', provinsi_kode: '16' },
  { kode: '16.07', nama: 'KABUPATEN BANYUASIN', provinsi_kode: '16' },
  { kode: '16.08', nama: 'KABUPATEN OGAN KOMERING ULU SELATAN', provinsi_kode: '16' },
  { kode: '16.09', nama: 'KABUPATEN OGAN KOMERING ULU TIMUR', provinsi_kode: '16' },
  { kode: '16.10', nama: 'KABUPATEN OGAN ILIR', provinsi_kode: '16' },
  { kode: '16.11', nama: 'KABUPATEN EMPAT LAWANG', provinsi_kode: '16' },
  { kode: '16.12', nama: 'KABUPATEN PENUKAL ABAB LEMATANG ILIR', provinsi_kode: '16' },
  { kode: '16.13', nama: 'KABUPATEN MUSI RAWAS UTARA', provinsi_kode: '16' },
  { kode: '16.71', nama: 'KOTA PALEMBANG', provinsi_kode: '16' },
  { kode: '16.72', nama: 'KOTA PRABUMULIH', provinsi_kode: '16' },
  { kode: '16.73', nama: 'KOTA PAGAR ALAM', provinsi_kode: '16' },
  { kode: '16.74', nama: 'KOTA LUBUKLINGGAU', provinsi_kode: '16' },
  // Bengkulu (17)
  { kode: '17.01', nama: 'KABUPATEN BENGKULU SELATAN', provinsi_kode: '17' },
  { kode: '17.02', nama: 'KABUPATEN REJANG LEBONG', provinsi_kode: '17' },
  { kode: '17.03', nama: 'KABUPATEN BENGKULU UTARA', provinsi_kode: '17' },
  { kode: '17.04', nama: 'KABUPATEN KAUR', provinsi_kode: '17' },
  { kode: '17.05', nama: 'KABUPATEN SELUMA', provinsi_kode: '17' },
  { kode: '17.06', nama: 'KABUPATEN MUKOMUKO', provinsi_kode: '17' },
  { kode: '17.07', nama: 'KABUPATEN LEBONG', provinsi_kode: '17' },
  { kode: '17.08', nama: 'KABUPATEN KEPAHIANG', provinsi_kode: '17' },
  { kode: '17.09', nama: 'KABUPATEN BENGKULU TENGAH', provinsi_kode: '17' },
  { kode: '17.71', nama: 'KOTA BENGKULU', provinsi_kode: '17' },
  // Lampung (18)
  { kode: '18.01', nama: 'KABUPATEN LAMPUNG BARAT', provinsi_kode: '18' },
  { kode: '18.02', nama: 'KABUPATEN TANGGAMUS', provinsi_kode: '18' },
  { kode: '18.03', nama: 'KABUPATEN LAMPUNG SELATAN', provinsi_kode: '18' },
  { kode: '18.04', nama: 'KABUPATEN LAMPUNG TIMUR', provinsi_kode: '18' },
  { kode: '18.05', nama: 'KABUPATEN LAMPUNG TENGAH', provinsi_kode: '18' },
  { kode: '18.06', nama: 'KABUPATEN LAMPUNG UTARA', provinsi_kode: '18' },
  { kode: '18.07', nama: 'KABUPATEN WAY KANAN', provinsi_kode: '18' },
  { kode: '18.08', nama: 'KABUPATEN TULANGBAWANG', provinsi_kode: '18' },
  { kode: '18.09', nama: 'KABUPATEN PESAWARAN', provinsi_kode: '18' },
  { kode: '18.10', nama: 'KABUPATEN PRINGSEWU', provinsi_kode: '18' },
  { kode: '18.11', nama: 'KABUPATEN MESUJI', provinsi_kode: '18' },
  { kode: '18.12', nama: 'KABUPATEN TULANG BAWANG BARAT', provinsi_kode: '18' },
  { kode: '18.13', nama: 'KABUPATEN PESISIR BARAT', provinsi_kode: '18' },
  { kode: '18.71', nama: 'KOTA BANDAR LAMPUNG', provinsi_kode: '18' },
  { kode: '18.72', nama: 'KOTA METRO', provinsi_kode: '18' },
  // Kepulauan Bangka Belitung (19)
  { kode: '19.01', nama: 'KABUPATEN BANGKA', provinsi_kode: '19' },
  { kode: '19.02', nama: 'KABUPATEN BELITUNG', provinsi_kode: '19' },
  { kode: '19.03', nama: 'KABUPATEN BANGKA BARAT', provinsi_kode: '19' },
  { kode: '19.04', nama: 'KABUPATEN BANGKA TENGAH', provinsi_kode: '19' },
  { kode: '19.05', nama: 'KABUPATEN BANGKA SELATAN', provinsi_kode: '19' },
  { kode: '19.06', nama: 'KABUPATEN BELITUNG TIMUR', provinsi_kode: '19' },
  { kode: '19.71', nama: 'KOTA PANGKALPINANG', provinsi_kode: '19' },
  // Kepulauan Riau (21)
  { kode: '21.01', nama: 'KABUPATEN KARIMUN', provinsi_kode: '21' },
  { kode: '21.02', nama: 'KABUPATEN BINTAN', provinsi_kode: '21' },
  { kode: '21.03', nama: 'KABUPATEN NATUNA', provinsi_kode: '21' },
  { kode: '21.04', nama: 'KABUPATEN LINGGA', provinsi_kode: '21' },
  { kode: '21.05', nama: 'KABUPATEN KEPULAUAN ANAMBAS', provinsi_kode: '21' },
  { kode: '21.71', nama: 'KOTA BATAM', provinsi_kode: '21' },
  { kode: '21.72', nama: 'KOTA TANJUNGPINANG', provinsi_kode: '21' },
  // DKI Jakarta (31)
  { kode: '31.01', nama: 'KABUPATEN KEPULAUAN SERIBU', provinsi_kode: '31' },
  { kode: '31.71', nama: 'KOTA JAKARTA SELATAN', provinsi_kode: '31' },
  { kode: '31.72', nama: 'KOTA JAKARTA TIMUR', provinsi_kode: '31' },
  { kode: '31.73', nama: 'KOTA JAKARTA PUSAT', provinsi_kode: '31' },
  { kode: '31.74', nama: 'KOTA JAKARTA BARAT', provinsi_kode: '31' },
  { kode: '31.75', nama: 'KOTA JAKARTA UTARA', provinsi_kode: '31' },
  // Jawa Barat (32)
  { kode: '32.01', nama: 'KABUPATEN BOGOR', provinsi_kode: '32' },
  { kode: '32.02', nama: 'KABUPATEN SUKABUMI', provinsi_kode: '32' },
  { kode: '32.03', nama: 'KABUPATEN CIANJUR', provinsi_kode: '32' },
  { kode: '32.04', nama: 'KABUPATEN BANDUNG', provinsi_kode: '32' },
  { kode: '32.05', nama: 'KABUPATEN GARUT', provinsi_kode: '32' },
  { kode: '32.06', nama: 'KABUPATEN TASIKMALAYA', provinsi_kode: '32' },
  { kode: '32.07', nama: 'KABUPATEN CIAMIS', provinsi_kode: '32' },
  { kode: '32.08', nama: 'KABUPATEN KUNINGAN', provinsi_kode: '32' },
  { kode: '32.09', nama: 'KABUPATEN CIREBON', provinsi_kode: '32' },
  { kode: '32.10', nama: 'KABUPATEN MAJALENGKA', provinsi_kode: '32' },
  { kode: '32.11', nama: 'KABUPATEN SUMEDANG', provinsi_kode: '32' },
  { kode: '32.12', nama: 'KABUPATEN INDRAMAYU', provinsi_kode: '32' },
  { kode: '32.13', nama: 'KABUPATEN SUBANG', provinsi_kode: '32' },
  { kode: '32.14', nama: 'KABUPATEN PURWAKARTA', provinsi_kode: '32' },
  { kode: '32.15', nama: 'KABUPATEN KARAWANG', provinsi_kode: '32' },
  { kode: '32.16', nama: 'KABUPATEN BEKASI', provinsi_kode: '32' },
  { kode: '32.17', nama: 'KABUPATEN BANDUNG BARAT', provinsi_kode: '32' },
  { kode: '32.18', nama: 'KABUPATEN PANGANDARAN', provinsi_kode: '32' },
  { kode: '32.71', nama: 'KOTA BOGOR', provinsi_kode: '32' },
  { kode: '32.72', nama: 'KOTA SUKABUMI', provinsi_kode: '32' },
  { kode: '32.73', nama: 'KOTA BANDUNG', provinsi_kode: '32' },
  { kode: '32.74', nama: 'KOTA CIREBON', provinsi_kode: '32' },
  { kode: '32.75', nama: 'KOTA BEKASI', provinsi_kode: '32' },
  { kode: '32.76', nama: 'KOTA DEPOK', provinsi_kode: '32' },
  { kode: '32.77', nama: 'KOTA CIMAHI', provinsi_kode: '32' },
  { kode: '32.78', nama: 'KOTA TASIKMALAYA', provinsi_kode: '32' },
  { kode: '32.79', nama: 'KOTA BANJAR', provinsi_kode: '32' },
  // Jawa Tengah (33)
  { kode: '33.01', nama: 'KABUPATEN CILACAP', provinsi_kode: '33' },
  { kode: '33.02', nama: 'KABUPATEN BANYUMAS', provinsi_kode: '33' },
  { kode: '33.03', nama: 'KABUPATEN PURBALINGGA', provinsi_kode: '33' },
  { kode: '33.04', nama: 'KABUPATEN BANJARNEGARA', provinsi_kode: '33' },
  { kode: '33.05', nama: 'KABUPATEN KEBUMEN', provinsi_kode: '33' },
  { kode: '33.06', nama: 'KABUPATEN PURWOREJO', provinsi_kode: '33' },
  { kode: '33.07', nama: 'KABUPATEN WONOSOBO', provinsi_kode: '33' },
  { kode: '33.08', nama: 'KABUPATEN MAGELANG', provinsi_kode: '33' },
  { kode: '33.09', nama: 'KABUPATEN BOYOLALI', provinsi_kode: '33' },
  { kode: '33.10', nama: 'KABUPATEN KLATEN', provinsi_kode: '33' },
  { kode: '33.11', nama: 'KABUPATEN SUKOHARJO', provinsi_kode: '33' },
  { kode: '33.12', nama: 'KABUPATEN WONOGIRI', provinsi_kode: '33' },
  { kode: '33.13', nama: 'KABUPATEN KARANGANYAR', provinsi_kode: '33' },
  { kode: '33.14', nama: 'KABUPATEN SRAGEN', provinsi_kode: '33' },
  { kode: '33.15', nama: 'KABUPATEN GROBOGAN', provinsi_kode: '33' },
  { kode: '33.16', nama: 'KABUPATEN BLORA', provinsi_kode: '33' },
  { kode: '33.17', nama: 'KABUPATEN REMBANG', provinsi_kode: '33' },
  { kode: '33.18', nama: 'KABUPATEN PATI', provinsi_kode: '33' },
  { kode: '33.19', nama: 'KABUPATEN KUDUS', provinsi_kode: '33' },
  { kode: '33.20', nama: 'KABUPATEN JEPARA', provinsi_kode: '33' },
  { kode: '33.21', nama: 'KABUPATEN DEMAK', provinsi_kode: '33' },
  { kode: '33.22', nama: 'KABUPATEN SEMARANG', provinsi_kode: '33' },
  { kode: '33.23', nama: 'KABUPATEN TEMANGGUNG', provinsi_kode: '33' },
  { kode: '33.24', nama: 'KABUPATEN KENDAL', provinsi_kode: '33' },
  { kode: '33.25', nama: 'KABUPATEN BATANG', provinsi_kode: '33' },
  { kode: '33.26', nama: 'KABUPATEN PEKALONGAN', provinsi_kode: '33' },
  { kode: '33.27', nama: 'KABUPATEN PEMALANG', provinsi_kode: '33' },
  { kode: '33.28', nama: 'KABUPATEN TEGAL', provinsi_kode: '33' },
  { kode: '33.29', nama: 'KABUPATEN BREBES', provinsi_kode: '33' },
  { kode: '33.71', nama: 'KOTA MAGELANG', provinsi_kode: '33' },
  { kode: '33.72', nama: 'KOTA SURAKARTA', provinsi_kode: '33' },
  { kode: '33.73', nama: 'KOTA SALATIGA', provinsi_kode: '33' },
  { kode: '33.74', nama: 'KOTA SEMARANG', provinsi_kode: '33' },
  { kode: '33.75', nama: 'KOTA PEKALONGAN', provinsi_kode: '33' },
  { kode: '33.76', nama: 'KOTA TEGAL', provinsi_kode: '33' },
  // DI Yogyakarta (34)
  { kode: '34.01', nama: 'KABUPATEN KULON PROGO', provinsi_kode: '34' },
  { kode: '34.02', nama: 'KABUPATEN BANTUL', provinsi_kode: '34' },
  { kode: '34.03', nama: 'KABUPATEN GUNUNGKIDUL', provinsi_kode: '34' },
  { kode: '34.04', nama: 'KABUPATEN SLEMAN', provinsi_kode: '34' },
  { kode: '34.71', nama: 'KOTA YOGYAKARTA', provinsi_kode: '34' },
  // Jawa Timur (35)
  { kode: '35.01', nama: 'KABUPATEN PACITAN', provinsi_kode: '35' },
  { kode: '35.02', nama: 'KABUPATEN PONOROGO', provinsi_kode: '35' },
  { kode: '35.03', nama: 'KABUPATEN TRENGGALEK', provinsi_kode: '35' },
  { kode: '35.04', nama: 'KABUPATEN TULUNGAGUNG', provinsi_kode: '35' },
  { kode: '35.05', nama: 'KABUPATEN BLITAR', provinsi_kode: '35' },
  { kode: '35.06', nama: 'KABUPATEN KEDIRI', provinsi_kode: '35' },
  { kode: '35.07', nama: 'KABUPATEN MALANG', provinsi_kode: '35' },
  { kode: '35.08', nama: 'KABUPATEN LUMAJANG', provinsi_kode: '35' },
  { kode: '35.09', nama: 'KABUPATEN JEMBER', provinsi_kode: '35' },
  { kode: '35.10', nama: 'KABUPATEN BANYUWANGI', provinsi_kode: '35' },
  { kode: '35.11', nama: 'KABUPATEN BONDOWOSO', provinsi_kode: '35' },
  { kode: '35.12', nama: 'KABUPATEN SITUBONDO', provinsi_kode: '35' },
  { kode: '35.13', nama: 'KABUPATEN PROBOLINGGO', provinsi_kode: '35' },
  { kode: '35.14', nama: 'KABUPATEN PASURUAN', provinsi_kode: '35' },
  { kode: '35.15', nama: 'KABUPATEN SIDOARJO', provinsi_kode: '35' },
  { kode: '35.16', nama: 'KABUPATEN MOJOKERTO', provinsi_kode: '35' },
  { kode: '35.17', nama: 'KABUPATEN JOMBANG', provinsi_kode: '35' },
  { kode: '35.18', nama: 'KABUPATEN NGANJUK', provinsi_kode: '35' },
  { kode: '35.19', nama: 'KABUPATEN MADIUN', provinsi_kode: '35' },
  { kode: '35.20', nama: 'KABUPATEN MAGETAN', provinsi_kode: '35' },
  { kode: '35.21', nama: 'KABUPATEN NGAWI', provinsi_kode: '35' },
  { kode: '35.22', nama: 'KABUPATEN BOJONEGORO', provinsi_kode: '35' },
  { kode: '35.23', nama: 'KABUPATEN TUBAN', provinsi_kode: '35' },
  { kode: '35.24', nama: 'KABUPATEN LAMONGAN', provinsi_kode: '35' },
  { kode: '35.25', nama: 'KABUPATEN GRESIK', provinsi_kode: '35' },
  { kode: '35.26', nama: 'KABUPATEN BANGKALAN', provinsi_kode: '35' },
  { kode: '35.27', nama: 'KABUPATEN SAMPANG', provinsi_kode: '35' },
  { kode: '35.28', nama: 'KABUPATEN PAMEKASAN', provinsi_kode: '35' },
  { kode: '35.29', nama: 'KABUPATEN SUMENEP', provinsi_kode: '35' },
  { kode: '35.71', nama: 'KOTA KEDIRI', provinsi_kode: '35' },
  { kode: '35.72', nama: 'KOTA BLITAR', provinsi_kode: '35' },
  { kode: '35.73', nama: 'KOTA MALANG', provinsi_kode: '35' },
  { kode: '35.74', nama: 'KOTA PROBOLINGGO', provinsi_kode: '35' },
  { kode: '35.75', nama: 'KOTA PASURUAN', provinsi_kode: '35' },
  { kode: '35.76', nama: 'KOTA MOJOKERTO', provinsi_kode: '35' },
  { kode: '35.77', nama: 'KOTA MADIUN', provinsi_kode: '35' },
  { kode: '35.78', nama: 'KOTA SURABAYA', provinsi_kode: '35' },
  { kode: '35.79', nama: 'KOTA BATU', provinsi_kode: '35' },
  // Banten (36)
  { kode: '36.01', nama: 'KABUPATEN PANDEGLANG', provinsi_kode: '36' },
  { kode: '36.02', nama: 'KABUPATEN LEBAK', provinsi_kode: '36' },
  { kode: '36.03', nama: 'KABUPATEN TANGERANG', provinsi_kode: '36' },
  { kode: '36.04', nama: 'KABUPATEN SERANG', provinsi_kode: '36' },
  { kode: '36.71', nama: 'KOTA TANGERANG', provinsi_kode: '36' },
  { kode: '36.72', nama: 'KOTA CILEGON', provinsi_kode: '36' },
  { kode: '36.73', nama: 'KOTA SERANG', provinsi_kode: '36' },
  { kode: '36.74', nama: 'KOTA TANGERANG SELATAN', provinsi_kode: '36' },
  // Bali (51)
  { kode: '51.01', nama: 'KABUPATEN JEMBRANA', provinsi_kode: '51' },
  { kode: '51.02', nama: 'KABUPATEN TABANAN', provinsi_kode: '51' },
  { kode: '51.03', nama: 'KABUPATEN BADUNG', provinsi_kode: '51' },
  { kode: '51.04', nama: 'KABUPATEN GIANYAR', provinsi_kode: '51' },
  { kode: '51.05', nama: 'KABUPATEN KLUNGKUNG', provinsi_kode: '51' },
  { kode: '51.06', nama: 'KABUPATEN BANGLI', provinsi_kode: '51' },
  { kode: '51.07', nama: 'KABUPATEN KARANGASEM', provinsi_kode: '51' },
  { kode: '51.08', nama: 'KABUPATEN BULELENG', provinsi_kode: '51' },
  { kode: '51.71', nama: 'KOTA DENPASAR', provinsi_kode: '51' },
  // Nusa Tenggara Barat (52)
  { kode: '52.01', nama: 'KABUPATEN LOMBOK BARAT', provinsi_kode: '52' },
  { kode: '52.02', nama: 'KABUPATEN LOMBOK TENGAH', provinsi_kode: '52' },
  { kode: '52.03', nama: 'KABUPATEN LOMBOK TIMUR', provinsi_kode: '52' },
  { kode: '52.04', nama: 'KABUPATEN SUMBAWA', provinsi_kode: '52' },
  { kode: '52.05', nama: 'KABUPATEN DOMPU', provinsi_kode: '52' },
  { kode: '52.06', nama: 'KABUPATEN BIMA', provinsi_kode: '52' },
  { kode: '52.07', nama: 'KABUPATEN SUMBAWA BARAT', provinsi_kode: '52' },
  { kode: '52.08', nama: 'KABUPATEN LOMBOK UTARA', provinsi_kode: '52' },
  { kode: '52.71', nama: 'KOTA MATARAM', provinsi_kode: '52' },
  { kode: '52.72', nama: 'KOTA BIMA', provinsi_kode: '52' },
  // Nusa Tenggara Timur (53)
  { kode: '53.01', nama: 'KABUPATEN SUMBA BARAT', provinsi_kode: '53' },
  { kode: '53.02', nama: 'KABUPATEN SUMBA TIMUR', provinsi_kode: '53' },
  { kode: '53.03', nama: 'KABUPATEN KUPANG', provinsi_kode: '53' },
  { kode: '53.04', nama: 'KABUPATEN TIMOR TENGAH SELATAN', provinsi_kode: '53' },
  { kode: '53.05', nama: 'KABUPATEN TIMOR TENGAH UTARA', provinsi_kode: '53' },
  { kode: '53.06', nama: 'KABUPATEN BELU', provinsi_kode: '53' },
  { kode: '53.07', nama: 'KABUPATEN ALOR', provinsi_kode: '53' },
  { kode: '53.08', nama: 'KABUPATEN LEMBATA', provinsi_kode: '53' },
  { kode: '53.09', nama: 'KABUPATEN FLORES TIMUR', provinsi_kode: '53' },
  { kode: '53.10', nama: 'KABUPATEN SIKKA', provinsi_kode: '53' },
  { kode: '53.11', nama: 'KABUPATEN ENDE', provinsi_kode: '53' },
  { kode: '53.12', nama: 'KABUPATEN NGADA', provinsi_kode: '53' },
  { kode: '53.13', nama: 'KABUPATEN MANGGARAI', provinsi_kode: '53' },
  { kode: '53.14', nama: 'KABUPATEN ROTE NDAO', provinsi_kode: '53' },
  { kode: '53.15', nama: 'KABUPATEN MANGGARAI BARAT', provinsi_kode: '53' },
  { kode: '53.16', nama: 'KABUPATEN SUMBA TENGAH', provinsi_kode: '53' },
  { kode: '53.17', nama: 'KABUPATEN SUMBA BARAT DAYA', provinsi_kode: '53' },
  { kode: '53.18', nama: 'KABUPATEN NAGEKEO', provinsi_kode: '53' },
  { kode: '53.19', nama: 'KABUPATEN MANGGARAI TIMUR', provinsi_kode: '53' },
  { kode: '53.20', nama: 'KABUPATEN SABU RAIJUA', provinsi_kode: '53' },
  { kode: '53.21', nama: 'KABUPATEN MALAKA', provinsi_kode: '53' },
  { kode: '53.71', nama: 'KOTA KUPANG', provinsi_kode: '53' },
  // Kalimantan Barat (61)
  { kode: '61.01', nama: 'KABUPATEN SAMBAS', provinsi_kode: '61' },
  { kode: '61.02', nama: 'KABUPATEN BENGKAYANG', provinsi_kode: '61' },
  { kode: '61.03', nama: 'KABUPATEN LANDAK', provinsi_kode: '61' },
  { kode: '61.04', nama: 'KABUPATEN MEMPAWAH', provinsi_kode: '61' },
  { kode: '61.05', nama: 'KABUPATEN SANGGAU', provinsi_kode: '61' },
  { kode: '61.06', nama: 'KABUPATEN KETAPANG', provinsi_kode: '61' },
  { kode: '61.07', nama: 'KABUPATEN SINTANG', provinsi_kode: '61' },
  { kode: '61.08', nama: 'KABUPATEN KAPUAS HULU', provinsi_kode: '61' },
  { kode: '61.09', nama: 'KABUPATEN SEKADAU', provinsi_kode: '61' },
  { kode: '61.10', nama: 'KABUPATEN MELAWI', provinsi_kode: '61' },
  { kode: '61.11', nama: 'KABUPATEN KAYONG UTARA', provinsi_kode: '61' },
  { kode: '61.12', nama: 'KABUPATEN KUBU RAYA', provinsi_kode: '61' },
  { kode: '61.71', nama: 'KOTA PONTIANAK', provinsi_kode: '61' },
  { kode: '61.72', nama: 'KOTA SINGKAWANG', provinsi_kode: '61' },
  // Kalimantan Tengah (62)
  { kode: '62.01', nama: 'KABUPATEN KOTAWARINGIN BARAT', provinsi_kode: '62' },
  { kode: '62.02', nama: 'KABUPATEN KOTAWARINGIN TIMUR', provinsi_kode: '62' },
  { kode: '62.03', nama: 'KABUPATEN KAPUAS', provinsi_kode: '62' },
  { kode: '62.04', nama: 'KABUPATEN BARITO SELATAN', provinsi_kode: '62' },
  { kode: '62.05', nama: 'KABUPATEN BARITO UTARA', provinsi_kode: '62' },
  { kode: '62.06', nama: 'KABUPATEN SUKAMARA', provinsi_kode: '62' },
  { kode: '62.07', nama: 'KABUPATEN LAMANDAU', provinsi_kode: '62' },
  { kode: '62.08', nama: 'KABUPATEN SERUYAN', provinsi_kode: '62' },
  { kode: '62.09', nama: 'KABUPATEN KATINGAN', provinsi_kode: '62' },
  { kode: '62.10', nama: 'KABUPATEN PULANG PISAU', provinsi_kode: '62' },
  { kode: '62.11', nama: 'KABUPATEN GUNUNG MAS', provinsi_kode: '62' },
  { kode: '62.12', nama: 'KABUPATEN BARITO TIMUR', provinsi_kode: '62' },
  { kode: '62.13', nama: 'KABUPATEN MURUNG RAYA', provinsi_kode: '62' },
  { kode: '62.71', nama: 'KOTA PALANGKA RAYA', provinsi_kode: '62' },
  // Kalimantan Selatan (63)
  { kode: '63.01', nama: 'KABUPATEN TANAH LAUT', provinsi_kode: '63' },
  { kode: '63.02', nama: 'KABUPATEN KOTABARU', provinsi_kode: '63' },
  { kode: '63.03', nama: 'KABUPATEN BANJAR', provinsi_kode: '63' },
  { kode: '63.04', nama: 'KABUPATEN BARITO KUALA', provinsi_kode: '63' },
  { kode: '63.05', nama: 'KABUPATEN TAPIN', provinsi_kode: '63' },
  { kode: '63.06', nama: 'KABUPATEN HULU SUNGAI SELATAN', provinsi_kode: '63' },
  { kode: '63.07', nama: 'KABUPATEN HULU SUNGAI TENGAH', provinsi_kode: '63' },
  { kode: '63.08', nama: 'KABUPATEN HULU SUNGAI UTARA', provinsi_kode: '63' },
  { kode: '63.09', nama: 'KABUPATEN TABALONG', provinsi_kode: '63' },
  { kode: '63.10', nama: 'KABUPATEN TANAH BUMBU', provinsi_kode: '63' },
  { kode: '63.11', nama: 'KABUPATEN BALANGAN', provinsi_kode: '63' },
  { kode: '63.71', nama: 'KOTA BANJARMASIN', provinsi_kode: '63' },
  { kode: '63.72', nama: 'KOTA BANJARBARU', provinsi_kode: '63' },
  // Kalimantan Timur (64)
  { kode: '64.01', nama: 'KABUPATEN PASER', provinsi_kode: '64' },
  { kode: '64.02', nama: 'KABUPATEN KUTAI BARAT', provinsi_kode: '64' },
  { kode: '64.03', nama: 'KABUPATEN KUTAI KARTANEGARA', provinsi_kode: '64' },
  { kode: '64.04', nama: 'KABUPATEN KUTAI TIMUR', provinsi_kode: '64' },
  { kode: '64.05', nama: 'KABUPATEN BERAU', provinsi_kode: '64' },
  { kode: '64.08', nama: 'KABUPATEN PENAJAM PASER UTARA', provinsi_kode: '64' },
  { kode: '64.10', nama: 'KABUPATEN MAHAKAM ULU', provinsi_kode: '64' },
  { kode: '64.71', nama: 'KOTA BALIKPAPAN', provinsi_kode: '64' },
  { kode: '64.72', nama: 'KOTA SAMARINDA', provinsi_kode: '64' },
  { kode: '64.74', nama: 'KOTA BONTANG', provinsi_kode: '64' },
  // Kalimantan Utara (65)
  { kode: '65.01', nama: 'KABUPATEN MALINAU', provinsi_kode: '65' },
  { kode: '65.02', nama: 'KABUPATEN BULUNGAN', provinsi_kode: '65' },
  { kode: '65.03', nama: 'KABUPATEN TANA TIDUNG', provinsi_kode: '65' },
  { kode: '65.04', nama: 'KABUPATEN NUNUKAN', provinsi_kode: '65' },
  { kode: '65.71', nama: 'KOTA TARAKAN', provinsi_kode: '65' },
  // Sulawesi Utara (71)
  { kode: '71.01', nama: 'KABUPATEN BOLAANG MONGONDOW', provinsi_kode: '71' },
  { kode: '71.02', nama: 'KABUPATEN MINAHASA', provinsi_kode: '71' },
  { kode: '71.03', nama: 'KABUPATEN KEPULAUAN SANGIHE', provinsi_kode: '71' },
  { kode: '71.04', nama: 'KABUPATEN KEPULAUAN TALAUD', provinsi_kode: '71' },
  { kode: '71.05', nama: 'KABUPATEN MINAHASA SELATAN', provinsi_kode: '71' },
  { kode: '71.06', nama: 'KABUPATEN MINAHASA UTARA', provinsi_kode: '71' },
  { kode: '71.07', nama: 'KABUPATEN BOLAANG MONGONDOW UTARA', provinsi_kode: '71' },
  { kode: '71.08', nama: 'KABUPATEN SIAU TAGULANDANG BIARO', provinsi_kode: '71' },
  { kode: '71.09', nama: 'KABUPATEN MINAHASA TENGGARA', provinsi_kode: '71' },
  { kode: '71.10', nama: 'KABUPATEN BOLAANG MONGONDOW SELATAN', provinsi_kode: '71' },
  { kode: '71.11', nama: 'KABUPATEN BOLAANG MONGONDOW TIMUR', provinsi_kode: '71' },
  { kode: '71.71', nama: 'KOTA MANADO', provinsi_kode: '71' },
  { kode: '71.72', nama: 'KOTA BITUNG', provinsi_kode: '71' },
  { kode: '71.73', nama: 'KOTA TOMOHON', provinsi_kode: '71' },
  { kode: '71.74', nama: 'KOTA KOTAMOBAGU', provinsi_kode: '71' },
  // Sulawesi Tengah (72)
  { kode: '72.01', nama: 'KABUPATEN BANGGAI KEPULAUAN', provinsi_kode: '72' },
  { kode: '72.02', nama: 'KABUPATEN BANGGAI', provinsi_kode: '72' },
  { kode: '72.03', nama: 'KABUPATEN MOROWALI', provinsi_kode: '72' },
  { kode: '72.04', nama: 'KABUPATEN POSO', provinsi_kode: '72' },
  { kode: '72.05', nama: 'KABUPATEN DONGGALA', provinsi_kode: '72' },
  { kode: '72.06', nama: 'KABUPATEN TOLI-TOLI', provinsi_kode: '72' },
  { kode: '72.07', nama: 'KABUPATEN BUOL', provinsi_kode: '72' },
  { kode: '72.08', nama: 'KABUPATEN PARIGI MOUTONG', provinsi_kode: '72' },
  { kode: '72.09', nama: 'KABUPATEN TOJO UNA-UNA', provinsi_kode: '72' },
  { kode: '72.10', nama: 'KABUPATEN SIGI', provinsi_kode: '72' },
  { kode: '72.11', nama: 'KABUPATEN BANGGAI LAUT', provinsi_kode: '72' },
  { kode: '72.12', nama: 'KABUPATEN MOROWALI UTARA', provinsi_kode: '72' },
  { kode: '72.71', nama: 'KOTA PALU', provinsi_kode: '72' },
  // Sulawesi Selatan (73)
  { kode: '73.01', nama: 'KABUPATEN KEPULAUAN SELAYAR', provinsi_kode: '73' },
  { kode: '73.02', nama: 'KABUPATEN BULUKUMBA', provinsi_kode: '73' },
  { kode: '73.03', nama: 'KABUPATEN BANTAENG', provinsi_kode: '73' },
  { kode: '73.04', nama: 'KABUPATEN JENEPONTO', provinsi_kode: '73' },
  { kode: '73.05', nama: 'KABUPATEN TAKALAR', provinsi_kode: '73' },
  { kode: '73.06', nama: 'KABUPATEN GOWA', provinsi_kode: '73' },
  { kode: '73.07', nama: 'KABUPATEN SINJAI', provinsi_kode: '73' },
  { kode: '73.08', nama: 'KABUPATEN MAROS', provinsi_kode: '73' },
  { kode: '73.09', nama: 'KABUPATEN PANGKAJENE DAN KEPULAUAN', provinsi_kode: '73' },
  { kode: '73.10', nama: 'KABUPATEN BARRU', provinsi_kode: '73' },
  { kode: '73.11', nama: 'KABUPATEN BONE', provinsi_kode: '73' },
  { kode: '73.12', nama: 'KABUPATEN SOPPENG', provinsi_kode: '73' },
  { kode: '73.13', nama: 'KABUPATEN WAJO', provinsi_kode: '73' },
  { kode: '73.14', nama: 'KABUPATEN SIDENRENG RAPPANG', provinsi_kode: '73' },
  { kode: '73.15', nama: 'KABUPATEN PINRANG', provinsi_kode: '73' },
  { kode: '73.16', nama: 'KABUPATEN ENREKANG', provinsi_kode: '73' },
  { kode: '73.17', nama: 'KABUPATEN LUWU', provinsi_kode: '73' },
  { kode: '73.18', nama: 'KABUPATEN TANA TORAJA', provinsi_kode: '73' },
  { kode: '73.22', nama: 'KABUPATEN LUWU UTARA', provinsi_kode: '73' },
  { kode: '73.23', nama: 'KABUPATEN LUWU TIMUR', provinsi_kode: '73' },
  { kode: '73.24', nama: 'KABUPATEN TORAJA UTARA', provinsi_kode: '73' },
  { kode: '73.71', nama: 'KOTA MAKASSAR', provinsi_kode: '73' },
  { kode: '73.72', nama: 'KOTA PARE-PARE', provinsi_kode: '73' },
  { kode: '73.73', nama: 'KOTA PALOPO', provinsi_kode: '73' },
  // Sulawesi Tenggara (74)
  { kode: '74.01', nama: 'KABUPATEN BUTON', provinsi_kode: '74' },
  { kode: '74.02', nama: 'KABUPATEN MUNA', provinsi_kode: '74' },
  { kode: '74.03', nama: 'KABUPATEN KONAWE', provinsi_kode: '74' },
  { kode: '74.04', nama: 'KABUPATEN KOLAKA', provinsi_kode: '74' },
  { kode: '74.05', nama: 'KABUPATEN KONAWE SELATAN', provinsi_kode: '74' },
  { kode: '74.06', nama: 'KABUPATEN BOMBANA', provinsi_kode: '74' },
  { kode: '74.07', nama: 'KABUPATEN WAKATOBI', provinsi_kode: '74' },
  { kode: '74.08', nama: 'KABUPATEN KOLAKA UTARA', provinsi_kode: '74' },
  { kode: '74.09', nama: 'KABUPATEN BUTON UTARA', provinsi_kode: '74' },
  { kode: '74.10', nama: 'KABUPATEN KONAWE UTARA', provinsi_kode: '74' },
  { kode: '74.11', nama: 'KABUPATEN KOLAKA TIMUR', provinsi_kode: '74' },
  { kode: '74.12', nama: 'KABUPATEN KONAWE KEPULAUAN', provinsi_kode: '74' },
  { kode: '74.13', nama: 'KABUPATEN MUNA BARAT', provinsi_kode: '74' },
  { kode: '74.14', nama: 'KABUPATEN BUTON TENGAH', provinsi_kode: '74' },
  { kode: '74.15', nama: 'KABUPATEN BUTON SELATAN', provinsi_kode: '74' },
  { kode: '74.71', nama: 'KOTA KENDARI', provinsi_kode: '74' },
  { kode: '74.72', nama: 'KOTA BAUBAU', provinsi_kode: '74' },
  // Gorontalo (75)
  { kode: '75.01', nama: 'KABUPATEN BOALEMO', provinsi_kode: '75' },
  { kode: '75.02', nama: 'KABUPATEN GORONTALO', provinsi_kode: '75' },
  { kode: '75.03', nama: 'KABUPATEN POHUWATO', provinsi_kode: '75' },
  { kode: '75.04', nama: 'KABUPATEN BONE BOLANGO', provinsi_kode: '75' },
  { kode: '75.05', nama: 'KABUPATEN GORONTALO UTARA', provinsi_kode: '75' },
  { kode: '75.71', nama: 'KOTA GORONTALO', provinsi_kode: '75' },
  // Sulawesi Barat (76)
  { kode: '76.01', nama: 'KABUPATEN MAJENE', provinsi_kode: '76' },
  { kode: '76.02', nama: 'KABUPATEN POLEWALI MANDAR', provinsi_kode: '76' },
  { kode: '76.03', nama: 'KABUPATEN MAMASA', provinsi_kode: '76' },
  { kode: '76.04', nama: 'KABUPATEN MAMUJU', provinsi_kode: '76' },
  { kode: '76.05', nama: 'KABUPATEN MAMUJU TENGAH', provinsi_kode: '76' },
  { kode: '76.06', nama: 'KABUPATEN PASANGKAYU', provinsi_kode: '76' },
  // Maluku (81)
  { kode: '81.01', nama: 'KABUPATEN MALUKU TENGAH', provinsi_kode: '81' },
  { kode: '81.02', nama: 'KABUPATEN MALUKU TENGGARA', provinsi_kode: '81' },
  { kode: '81.03', nama: 'KABUPATEN KEPULAUAN TANIMBAR', provinsi_kode: '81' },
  { kode: '81.04', nama: 'KABUPATEN BURU', provinsi_kode: '81' },
  { kode: '81.05', nama: 'KABUPATEN SERAM BAGIAN TIMUR', provinsi_kode: '81' },
  { kode: '81.06', nama: 'KABUPATEN SERAM BAGIAN BARAT', provinsi_kode: '81' },
  { kode: '81.07', nama: 'KABUPATEN KEPULAUAN ARU', provinsi_kode: '81' },
  { kode: '81.08', nama: 'KABUPATEN MALUKU BARAT DAYA', provinsi_kode: '81' },
  { kode: '81.09', nama: 'KABUPATEN BURU SELATAN', provinsi_kode: '81' },
  { kode: '81.71', nama: 'KOTA AMBON', provinsi_kode: '81' },
  { kode: '81.72', nama: 'KOTA TUAL', provinsi_kode: '81' },
  // Maluku Utara (82)
  { kode: '82.01', nama: 'KABUPATEN HALMAHERA BARAT', provinsi_kode: '82' },
  { kode: '82.02', nama: 'KABUPATEN HALMAHERA TENGAH', provinsi_kode: '82' },
  { kode: '82.03', nama: 'KABUPATEN KEPULAUAN SULA', provinsi_kode: '82' },
  { kode: '82.04', nama: 'KABUPATEN HALMAHERA SELATAN', provinsi_kode: '82' },
  { kode: '82.05', nama: 'KABUPATEN HALMAHERA UTARA', provinsi_kode: '82' },
  { kode: '82.06', nama: 'KABUPATEN HALMAHERA TIMUR', provinsi_kode: '82' },
  { kode: '82.07', nama: 'KABUPATEN PULAU MOROTAI', provinsi_kode: '82' },
  { kode: '82.08', nama: 'KABUPATEN PULAU TALIABU', provinsi_kode: '82' },
  { kode: '82.71', nama: 'KOTA TERNATE', provinsi_kode: '82' },
  { kode: '82.72', nama: 'KOTA TIDORE KEPULAUAN', provinsi_kode: '82' },
  // Papua Barat (91)
  { kode: '91.01', nama: 'KABUPATEN FAK-FAK', provinsi_kode: '91' },
  { kode: '91.02', nama: 'KABUPATEN KAIMANA', provinsi_kode: '91' },
  { kode: '91.03', nama: 'KABUPATEN TELUK WONDAMA', provinsi_kode: '91' },
  { kode: '91.04', nama: 'KABUPATEN TELUK BINTUNI', provinsi_kode: '91' },
  { kode: '91.05', nama: 'KABUPATEN MANOKWARI', provinsi_kode: '91' },
  { kode: '91.06', nama: 'KABUPATEN SORONG SELATAN', provinsi_kode: '91' },
  { kode: '91.07', nama: 'KABUPATEN SORONG', provinsi_kode: '91' },
  { kode: '91.08', nama: 'KABUPATEN RAJA AMPAT', provinsi_kode: '91' },
  { kode: '91.09', nama: 'KABUPATEN TAMBRAUW', provinsi_kode: '91' },
  { kode: '91.10', nama: 'KABUPATEN MAYBRAT', provinsi_kode: '91' },
  { kode: '91.11', nama: 'KABUPATEN MANOKWARI SELATAN', provinsi_kode: '91' },
  { kode: '91.12', nama: 'KABUPATEN PEGUNUNGAN ARFAK', provinsi_kode: '91' },
  { kode: '91.71', nama: 'KOTA SORONG', provinsi_kode: '91' },
  // Papua Tengah (92)
  { kode: '92.01', nama: 'KABUPATEN NABIRE', provinsi_kode: '92' },
  { kode: '92.02', nama: 'KABUPATEN PANIAI', provinsi_kode: '92' },
  { kode: '92.03', nama: 'KABUPATEN PUNCAK JAYA', provinsi_kode: '92' },
  { kode: '92.04', nama: 'KABUPATEN MIMIKA', provinsi_kode: '92' },
  { kode: '92.05', nama: 'KABUPATEN PUNCAK', provinsi_kode: '92' },
  { kode: '92.06', nama: 'KABUPATEN DOGIYAI', provinsi_kode: '92' },
  { kode: '92.07', nama: 'KABUPATEN INTAN JAYA', provinsi_kode: '92' },
  { kode: '92.08', nama: 'KABUPATEN DEIYAI', provinsi_kode: '92' },
  // Papua Pegunungan (93)
  { kode: '93.01', nama: 'KABUPATEN JAYAWIJAYA', provinsi_kode: '93' },
  { kode: '93.02', nama: 'KABUPATEN PEGUNUNGAN BINTANG', provinsi_kode: '93' },
  { kode: '93.03', nama: 'KABUPATEN YAHUKIMO', provinsi_kode: '93' },
  { kode: '93.04', nama: 'KABUPATEN TOLIKARA', provinsi_kode: '93' },
  { kode: '93.05', nama: 'KABUPATEN MAMBERAMO TENGAH', provinsi_kode: '93' },
  { kode: '93.06', nama: 'KABUPATEN YALIMO', provinsi_kode: '93' },
  { kode: '93.07', nama: 'KABUPATEN LANNY JAYA', provinsi_kode: '93' },
  { kode: '93.08', nama: 'KABUPATEN NDUGA', provinsi_kode: '93' },
  { kode: '93.09', nama: 'KABUPATEN PUNCAK JAYA', provinsi_kode: '93' },
  // Papua (94)
  { kode: '94.01', nama: 'KABUPATEN MERAUKE', provinsi_kode: '94' },
  { kode: '94.02', nama: 'KABUPATEN JAYAPURA', provinsi_kode: '94' },
  { kode: '94.03', nama: 'KABUPATEN BIAK NUMFOR', provinsi_kode: '94' },
  { kode: '94.04', nama: 'KABUPATEN KEPULAUAN YAPEN', provinsi_kode: '94' },
  { kode: '94.05', nama: 'KABUPATEN WAROPEN', provinsi_kode: '94' },
  { kode: '94.06', nama: 'KABUPATEN SUPIORI', provinsi_kode: '94' },
  { kode: '94.07', nama: 'KABUPATEN MAMBERAMO RAYA', provinsi_kode: '94' },
  { kode: '94.08', nama: 'KABUPATEN SARMI', provinsi_kode: '94' },
  { kode: '94.09', nama: 'KABUPATEN KEEROM', provinsi_kode: '94' },
  { kode: '94.71', nama: 'KOTA JAYAPURA', provinsi_kode: '94' },
  // Papua Selatan (95)
  { kode: '95.01', nama: 'KABUPATEN BOVEN DIGOEL', provinsi_kode: '95' },
  { kode: '95.02', nama: 'KABUPATEN MAPPI', provinsi_kode: '95' },
  { kode: '95.03', nama: 'KABUPATEN ASMAT', provinsi_kode: '95' },
  { kode: '95.04', nama: 'KABUPATEN MERAUKE', provinsi_kode: '95' },
  // Papua Barat Daya (96)
  { kode: '96.01', nama: 'KABUPATEN SORONG', provinsi_kode: '96' },
  { kode: '96.02', nama: 'KABUPATEN SORONG SELATAN', provinsi_kode: '96' },
  { kode: '96.03', nama: 'KABUPATEN RAJA AMPAT', provinsi_kode: '96' },
  { kode: '96.04', nama: 'KABUPATEN TAMBRAUW', provinsi_kode: '96' },
  { kode: '96.05', nama: 'KABUPATEN MAYBRAT', provinsi_kode: '96' },
  { kode: '96.71', nama: 'KOTA SORONG', provinsi_kode: '96' },
]

export function getKabupatenByProvinsi(provinsiKode: string): KabupatenKota[] {
  return KABUPATEN_KOTA.filter((k) => k.provinsi_kode === provinsiKode)
}

export function getProvinsiNama(kode: string): string {
  return PROVINSI.find((p) => p.kode === kode)?.nama ?? ''
}
