// Payment proof (bukti transfer) rules — shared by client forms and server actions.
// Proofs live in the private `payment-proofs` bucket (migration 092); DB columns
// (`transactions.receipt_url`, `booking_payments.proof_path`) store the object path.

export const PAYMENT_PROOF_BUCKET = 'payment-proofs'

export const PAYMENT_PROOF_REQUIRED_MSG = 'Bukti transfer wajib diunggah untuk pembayaran transfer.'

/** True when `method` is a transfer that needs a proof image.
 *  Covers transactions methods (`TRANSFER BCA`, `TRANSFER BANK KALBAR`) and
 *  order booking methods (`Non Tunai - BCA`, `Non Tunai - QRIS`, …). Cash and
 *  EDC card swipes (the EDC slip is the record) don't need one. */
export function requiresPaymentProof(method: string | null | undefined): boolean {
  if (!method) return false
  const m = method.toUpperCase()
  return m.startsWith('TRANSFER') || m.startsWith('NON TUNAI')
}

/** Object paths are generated by PaymentProofField: `YYYY/MM/<ts>-<rand>.webp`. */
export function isValidPaymentProofPath(path: string | null | undefined): path is string {
  return !!path && /^\d{4}\/\d{2}\/[\w-]+\.webp$/.test(path)
}

/** Proof rule when editing an existing payment: required when switching to a
 *  transfer method, or when the row already had a proof (it can be replaced,
 *  not dropped). Transfer rows recorded before proofs existed stay editable. */
export function isPaymentProofRequiredOnEdit(
  original: { method: string | null | undefined; proofPath: string | null | undefined },
  nextMethod: string | null | undefined,
): boolean {
  if (!requiresPaymentProof(nextMethod)) return false
  return nextMethod !== original.method || !!original.proofPath
}

/** Server-side guard for a new payment: returns an error message, or null when OK. */
export function paymentProofError(method: string | null | undefined, proofPath: string | null | undefined): string | null {
  if (proofPath != null && !isValidPaymentProofPath(proofPath)) return 'Bukti transfer tidak valid. Unggah ulang.'
  if (requiresPaymentProof(method) && !proofPath) return PAYMENT_PROOF_REQUIRED_MSG
  return null
}
